#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Purpose: Define distinct shared reports and source-specific outcome checks.
# Owns: Sixty-four event descriptions and separate benefit and harm terms.
# Threading: Read-only test data; the runtime processes each input on the GPU.
# Lifetime: One complete shared appraisal and recovery test.

# Inputs: Event index. Output: Source facts and outcome terms. Exit: Caller exceptions.

_ROWS = (
    ("observatory telescope alignment", "aligned the primary mirror", "cracked the eyepiece",
     (r"mirror|telescope", r"align|focus|clear"), (r"eyepiece", r"crack|broke|broken|damag")),
    ("sourdough baking at the bakery", "baked good sourdough loaves", "burned an oven mitt",
     (r"sourdough|loav|bread", r"bak|good|success"), (r"mitt", r"burn|scorch|damag")),
    ("violin string replacement", "tuned the violin to the correct pitch", "snapped the bow hair",
     (r"violin|pitch|string", r"tun|correct"), (r"bow|hair", r"snap|broke|broken|damag")),
    ("aquarium filter cleaning", "cleared the cloudy tank water", "broke the aquarium heater",
     (r"water|tank", r"clear|clean"), (r"heater", r"broke|broken|damag")),
    ("forest footbridge surveying", "mapped the footbridge accurately", "damaged the ranger radio",
     (r"footbridge|bridge", r"map|survey|accurat"), (r"radio", r"damag|broke|broken")),
    ("museum pottery cataloging", "cataloged the terracotta figures", "dropped and shattered a porcelain vase",
     (r"terracotta|figure", r"catalog|record|document"), (r"vase|porcelain", r"shatter|broke|broken|damag")),
    ("greenhouse tomato care", "saved the wilting tomato seedlings", "split an irrigation pipe",
     (r"tomato|seedling", r"sav|reviv|recover|restor"), (r"irrigation|pipe", r"split|broke|broken|damag")),
    ("bicycle gear adjustment", "fixed the bicycle gears", "bent the brake lever",
     (r"gear", r"fix|repair|adjust|restor"), (r"brake|lever", r"bent|bend|damag")),
    ("sailboat canvas repair", "stitched the torn sail", "tore the mooring rope",
     (r"sail|canvas", r"stitch|repair|mend"), (r"mooring|rope", r"tore|torn|tear|damag")),
    ("library atlas binding", "rebound the old atlas", "smeared ink across its map",
     (r"atlas|bind", r"rebound|rebind|repair|restor"), (r"map|ink", r"smear|stain|damag")),
    ("community mural painting", "finished the wall mural", "spilled blue pigment on the rug",
     (r"mural", r"finish|complet|paint"), (r"rug", r"spill|stain|pigment|damag")),
    ("beehive honey collection", "collected the honey successfully", "cracked a hive frame",
     (r"honey", r"collect|harvest|success"), (r"frame", r"crack|broke|broken|damag")),
    ("newspaper press setup", "printed legible newspaper pages", "broke the type handle",
     (r"newspaper|page", r"print|legib|clear"), (r"handle", r"broke|broken|damag")),
    ("cheddar cheese production", "completed the cheddar batch", "dented the steel vat",
     (r"cheddar|cheese", r"complet|finish|produc|success"), (r"vat", r"dent|damag")),
    ("ceramic tile firing", "glazed the ceramic tiles evenly", "fractured a kiln shelf",
     (r"tile", r"glaz|even|finish"), (r"shelf|shelv", r"fractur|crack|broke|broken|damag")),
    ("puppet theater preparation", "mended the puppet jaw", "ripped the velvet curtain",
     (r"puppet|jaw", r"mend|repair|fix"), (r"curtain|velvet", r"rip|tore|torn|tear|damag")),
    ("radio antenna installation", "improved the signal reception", "bent the antenna mast",
     (r"signal|reception", r"improv|clear|strong|restor"), (r"mast", r"bent|bend|damag")),
    ("piano key regulation", "balanced the piano keys", "scratched the piano lacquer",
     (r"key", r"balanc|adjust|regulat"), (r"lacquer|finish", r"scratch|damag")),
    ("historic coastline chart scanning", "digitized the coastline charts", "tore a vellum sheet",
     (r"coastline|chart", r"digitiz|scan|preserv"), (r"vellum|sheet", r"tore|torn|tear|damag")),
    ("pendulum clock restoration", "restored the pendulum motion", "snapped the mainspring",
     (r"pendulum|clock", r"restor|repair|work|mov"), (r"mainspring", r"snap|broke|broken|damag")),
    ("rose perfume distillation", "produced the rose essence", "broke the glass condenser",
     (r"rose|essence|perfume", r"produc|distill|extract|success"), (r"condenser", r"broke|broken|damag")),
    ("suede boot repair", "replaced the worn boot soles", "cut the suede upper",
     (r"sole", r"replac|repair|fix"), (r"suede|upper", r"cut|slash|damag")),
    ("box kite flight", "raised the box kite into the air", "tangled the flying lines",
     (r"kite", r"rais|flew|fly|flight|air|launch"), (r"line|string", r"tangl|knot|damag")),
    ("railway diorama assembly", "installed the miniature station", "chipped the model tunnel",
     (r"station", r"install|assembl|complet"), (r"tunnel", r"chip|damag|broke|broken")),
    ("chocolate truffle molding", "made smooth chocolate truffles", "split the mold tray",
     (r"truffle|chocolate", r"made|smooth|form|produc|success"), (r"tray|mold", r"split|crack|damag")),
    ("wool spinning", "spun strong wool yarn", "broke the treadle pivot",
     (r"wool|yarn", r"spun|spin|strong|produc"), (r"treadle|pivot", r"broke|broken|damag")),
    ("winery bottle labeling", "labeled the wine bottles correctly", "spilled wine on the ledger",
     (r"bottle|label", r"label|correct|complet"), (r"ledger", r"spill|stain|damag")),
    ("lighthouse optical cleaning", "cleared the lighthouse lens", "scratched the brass reflector",
     (r"lens", r"clear|clean|polish"), (r"reflector", r"scratch|damag")),
    ("wooden canoe restoration", "sealed the leaking canoe hull", "split a wooden paddle",
     (r"hull|canoe", r"seal|repair|fix|restor"), (r"paddle", r"split|crack|broke|broken|damag")),
    ("postage stamp sorting", "sorted the postage stamps", "peeled away a rare postmark",
     (r"stamp", r"sort|organiz|catalog"), (r"postmark", r"peel|remov|lost|damag")),
    ("wedding cake decoration", "finished the sugar flowers", "crushed the icing border",
     (r"flower", r"finish|complet|decorat|made"), (r"border", r"crush|damag")),
    ("carnival lantern display", "lit the hanging lanterns", "tore the paper dragon",
     (r"lantern", r"lit|light|illuminat"), (r"dragon", r"tore|torn|tear|rip|damag")),
    ("ammonite fossil preparation", "exposed the ammonite shell", "chipped a fossil rib",
     (r"ammonite|shell", r"expos|uncover|reveal|clean"), (r"rib", r"chip|damag|broke|broken")),
    ("coffee bean roasting", "roasted the coffee beans evenly", "burned a jute sack",
     (r"bean|coffee", r"roast|even|success"), (r"sack|jute", r"burn|scorch|damag")),
    ("marble mosaic installation", "arranged the marble pattern", "cracked the grout basin",
     (r"marble|mosaic|pattern", r"arrang|install|complet"), (r"grout|basin", r"crack|broke|broken|damag")),
    ("apple orchard pruning", "pruned the apple branches", "snapped the pruning shears",
     (r"apple|branch", r"prun|trim"), (r"shear", r"snap|broke|broken|damag")),
    ("film reel restoration", "spliced the film strip", "scratched the soundtrack",
     (r"film|strip", r"splic|repair|restor"), (r"soundtrack", r"scratch|damag")),
    ("watermill machinery repair", "restored the millwheel rotation", "stripped an axle gear",
     (r"millwheel|wheel", r"restor|rotat|repair|turn"), (r"axle|gear", r"strip|damag|broke|broken")),
    ("lace collar making", "finished the lace collar", "bent a lace bobbin",
     (r"collar|lace", r"finish|complet|made"), (r"bobbin", r"bent|bend|damag")),
    ("wooden chess set carving", "carved the wooden knight", "split the chessboard",
     (r"knight", r"carv|finish|complet"), (r"chessboard|board", r"split|crack|damag")),
    ("planetarium star projection", "focused the star images", "scratched the projection dome",
     (r"star|image", r"focus|clear"), (r"dome", r"scratch|damag")),
    ("dried mint packaging", "packed the dried mint leaves", "crushed the ceramic mortar",
     (r"mint|leav", r"pack|bag|complet"), (r"mortar", r"crush|broke|broken|damag")),
    ("snow globe assembly", "sealed the snow globe base", "chipped the glass snowman",
     (r"globe|base", r"seal|assembl|finish"), (r"snowman", r"chip|damag|broke|broken")),
    ("watch strap replacement", "fitted the strap buckle", "scratched the watch crystal",
     (r"buckle|strap", r"fit|replac|repair"), (r"crystal", r"scratch|damag")),
    ("stained glass panel joining", "joined the colored glass panels", "shattered an amber pane",
     (r"panel", r"join|assembl|finish"), (r"amber|pane", r"shatter|broke|broken|damag")),
    ("pipe organ restoration", "restored the organ pipes", "broke a bellows valve",
     (r"pipe|organ", r"restor|repair|fix"), (r"bellows|valve", r"broke|broken|damag")),
    ("banner embroidery", "stitched the gold lettering", "tore the banner lining",
     (r"letter|gold", r"stitch|embroider|finish"), (r"lining", r"tore|torn|tear|rip|damag")),
    ("seashell exhibit mounting", "mounted the conch shells", "cracked an abalone shell",
     (r"conch", r"mount|display|install"), (r"abalone", r"crack|broke|broken|damag")),
    ("wind chime tuning", "tuned the bronze tubes", "frayed the suspension cord",
     (r"tube|chime", r"tun|adjust"), (r"cord", r"fray|damag")),
    ("leather journal binding", "sewed the journal spine", "tore the parchment cover",
     (r"spine", r"sew|stitch|bind|bound|repair"), (r"parchment|cover", r"tore|torn|tear|damag")),
    ("botanical fern pressing", "pressed the fern fronds", "stained the linen blotter",
     (r"fern|frond", r"press|preserv|dry|dried"), (r"blotter|linen", r"stain|damag")),
    ("juggling club performance", "completed the juggling routine", "splintered a wooden club",
     (r"juggling|routine", r"complet|perform|finish|success"), (r"club", r"splinter|broke|broken|damag")),
    ("pottery wheel operation", "centered the clay bowl", "broke the foot pedal",
     (r"clay|bowl", r"center|form|shap"), (r"pedal", r"broke|broken|damag")),
    ("walking toy robot repair", "restored the walking motors", "cracked the battery housing",
     (r"motor|robot|walk", r"restor|repair|fix|work"), (r"battery|housing", r"crack|broke|broken|damag")),
    ("model ferry painting", "finished the red hull", "smudged the cabin decals",
     (r"hull", r"finish|paint|complet"), (r"decal|cabin", r"smudg|damag|smear")),
    ("silver spoon polishing", "removed the tarnish from the spoon", "bent the rosette handle",
     (r"spoon|tarnish", r"remov|polish|clean"), (r"rosette|handle", r"bent|bend|damag")),
    ("rug weaving", "wove the carpet runner", "snapped the loom shuttle",
     (r"runner|carpet|rug", r"wove|weav|finish|complet"), (r"shuttle", r"snap|broke|broken|damag")),
    ("garden fountain repair", "restored the fountain water jet", "chipped the stone basin",
     (r"fountain|jet", r"restor|repair|flow|work"), (r"stone|basin", r"chip|damag")),
    ("amber pendant polishing", "polished the amber pendant", "bent the silver clasp",
     (r"pendant|amber", r"polish|clean|finish"), (r"clasp", r"bent|bend|damag")),
    ("gingerbread cookie decoration", "decorated the gingerbread cookies", "crushed the sugar star",
     (r"gingerbread|cookie", r"decorat|finish|ic"), (r"star", r"crush|broke|broken|damag")),
    ("astronomy camera mounting", "balanced the astronomy camera", "cracked the tripod head",
     (r"camera", r"balanc|mount|stabil"), (r"tripod", r"crack|broke|broken|damag")),
    ("pumpkin harvesting", "collected the ripe pumpkins", "punctured the wheelbarrow tire",
     (r"pumpkin", r"collect|harvest|gather"), (r"tire|wheelbarrow", r"punctur|flat|damag")),
    ("ship in a bottle construction", "rigged the miniature schooner", "chipped the bottle neck",
     (r"schooner|ship", r"rig|assembl|construct|finish"), (r"bottle|neck", r"chip|damag|broke|broken")),
    ("armchair upholstery", "recovered the chair cushion", "tore the brocade armrest",
     (r"cushion", r"recover|upholster|cover|repair"), (r"brocade|armrest", r"tore|torn|tear|rip|damag")),
)

EVENTS = tuple(dict(zip(("topic", "benefit", "harm", "benefit_terms", "harm_terms"), row))
               for row in _ROWS)
