# Sound feature storage and workspace counts are independent of model parameters.
set(AOTX_AUDIO_FEATURE_ROWS "16384" CACHE STRING "The resident projected audio row capacity.")
set(AOTX_AUDIO_WORKERS "1" CACHE STRING "The number of simultaneous audio workspaces.")
set(AOTX_AUDIO_SOURCE_FRAMES "1440000" CACHE STRING "The decoded source frames per audio workspace.")
foreach(key AOTX_AUDIO_FEATURE_ROWS AOTX_AUDIO_WORKERS AOTX_AUDIO_SOURCE_FRAMES)
    string(LENGTH "${${key}}" digits)
    if(NOT "${${key}}" MATCHES "^[1-9][0-9]*$" OR digits GREATER 10 OR ${key} GREATER 4294967295)
        message(FATAL_ERROR "${key} exceeds the audio counter range")
    endif()
    target_compile_definitions(aotx_memory_config INTERFACE ${key}=${${key}}u)
endforeach()
if(AOTX_AUDIO_WORKERS GREATER 65535 OR AOTX_AUDIO_SOURCE_FRAMES GREATER 1440000)
    message(FATAL_ERROR "audio workspace count or source duration exceeds the supported format")
endif()
